### ISSUE TITLE
重庆集群更新新版本后，大面积FinalizeFailed提示找不到t_aux文件

### ISSUE THREAD

**Issue by wxswhh** [xjrwfilecoin/error_rust#4]
集群：重庆集群
miner位置：cq_node01
p1数据存储目录：/opt/hdd_pool/.lotusworker/
p2、c2数据存储目录：/opt/san/.lotusworker
版本：
build info: 51612442c3ce0bc667b83cd5dc4835ccdbe78d95
lotus version 0.10.2+git.95ffba5b2.dirty
错误扇区：从2479扇区开始，FinalizeSector状态的扇区都提交失败FinalizeFailed

**Comment by wxswhh** [comment]
No such file or directory (os error 2)
521.    2020-10-19 22:10:21 +0800 CST:  [event;sealing.SectorRetryFinalize]     {"User":{}}
522.    2020-10-19 22:10:21 +0800 CST:  [event;sealing.SectorFinalizeFailed]    {"User":{}}
        finalize sector: finalizing sector: could not read from path="/opt/hdd_pool/.lotusworker/cache/s-t010528-2479/t_aux"

Caused by:
    No such file or directory (os error 2)

**Comment by wxswhh** [comment]
@plotozhu

**Comment by plotozhu** [comment]
我查了没有hdd_pool这个目录

**Comment by BigOceanGG** [comment]
更新版本后未出现
